### ISSUE TITLE
CSS not responding

### ISSUE THREAD

**Issue by SirKira001** [Naxdy/latency-slider-de#25]
Hi! I downloaded this mod, and while it works perfectly on arenas, when entering quickplay it softlocks as it doesn't let me input a thing on my controller, it's still connected but when I press a button it doesn't to anything in-game, has anyone suffered from this before?

**Comment by SirKira001** [comment]
So I discovered that CSK's collection is what causes this issue when both plugins are enabled, is there a way to fix that?

**Comment by Emerald117** [comment]
I sent you a DM on Discord for a potential fix, but here do what is stated here: https://github.com/Naxdy/latency-slider-de/issues/22

**Comment by Naxdy** [comment]
Duplicate of https://github.com/Naxdy/latency-slider-de/issues/22
