### ISSUE TITLE
"latency slider DE will run with reduced features"

### ISSUE THREAD

**Issue by randyjama** [Naxdy/latency-slider-de#33]
Sorry if this isn't the right place to put it, as I'm not sure if this is a bug in the latest version of the mod.

After updating atmosphere and the game with the proper files everything works fine, but booting up smash I get a "latency slider DE will run with reduced features" notification. This disables the latency slider for quickplay in the character select screen. Everything else works fine for arenas with/without the 1302 code requirement.

Given it's a custom message I assume this is intentional, but why is this the case?

Thanks!

**Comment by randyjama** [comment]
Looking at previous comments and manual testing I'm seeing that the latency slider does indeed still work in quickplay, but the visuals aren't there to show the latency. Not sure if this is intended or not, but it still begs the question of why the original prompt in my first comment appeared.

**Comment by Silverback1776** [comment]
does your work in arenas?? can you tell its active? my doesn't work. I got the same message as you at the bootup of the game on reduced features. mine still shows on the top right corner but when i put it on a lowers number that i know will cause lag like 0 or 1 that games still runs smoothly as if its not active.

**Comment by Naxdy** [comment]
See the [release notes of 0.3.1](https://github.com/Naxdy/latency-slider-de/releases/tag/v0.3.1):

> If Ultimate Training Modpack is found to be installed, the latency display on quickplay / elite smash will be disabled. A notification will appear, which can be permanently disabled by placing an empty file called "dontannoyme.txt" in the root (the topmost) folder of your SD card.

This information is also displayed to you if you hit "Details" within the game.
