### ISSUE TITLE
Arena Latency Slider not working in arenas

### ISSUE THREAD

**Issue by Silverback1776** [Naxdy/latency-slider-de#34]
I got a notification that latency slider will have reduced features at the bootup of smash ultimate. Tested it out in some arenas and notice it's not active. shows on the top right corner like usual but no reduction of input delay. Any solutions to this??

**Comment by Silverback1776** [comment]
okay so i should remove the training mod and that will fix the latency mod?

**Comment by Silverback1776** [comment]
the way i measured it is by putting it at 0 or 1 in a arena. this always used to cause the game to be very slow the whole match. it doest do that anymore. thats how i test it. by putting it too low

**Comment by Silverback1776** [comment]
do i need to completely delete the training mod from my SD card? or can i just turn it off on my settings?

**Comment by Naxdy** [comment]
> the way i measured it is by putting it at 0 or 1 in a arena

Thing is, it's possible that you just got lucky and your opponent had a very good connection with you. A more reliable way to measure would be to set your input latency to something outlandish like 20, and checking whether you do, in fact, have about a third of a second additional delay.

> do i need to completely delete the training mod from my SD card? or can i just turn it off on my settings?

You don't need to remove the training modpack if you don't care about the text showing up in the CSS. See my comment in #33

**Comment by chimmychuck** [comment]
hey naxdy just curious, why does it not show if training modpack is selected? is this on purpose, if so why?

**Comment by Naxdy** [comment]
@chimmychuck See my comment here: https://github.com/Naxdy/latency-slider-de/issues/31#issuecomment-2409115935
